theme: jekyll-theme-cayman
title: Hofstra University
description: The largest private college on Long Island, New York, Hofstra University offers about 160 undergraduate programs and about 165 graduate degree programs.
